include:
  - ../shared-compose.yaml

services:
  web:
    volumes:
      - /home/ec2-user/arkad-backend/arkad/static:/app/arkad/static:ro

  nginx:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-production.rule=Host(`backend.arkadtlth.se`)"
      - "traefik.http.routers.app-production.entrypoints=websecure"
      - "traefik.http.routers.app-production.tls=true"
      - "traefik.http.routers.app-production.tls.certresolver=production"
    ports:
      - "8080:80"
    expose:
      - 80
