[tool.ruff]
line-length = 88
target-version = "py313"
exclude = [
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    "__pycache__",
    "venv",
    "migrations"
]

[tool.ruff.lint]
ignore = []
unfixable = []

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.mypy]
plugins = [
    "mypy_django_plugin.main",
]
strict = true
show_error_codes = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
strict_equality = true
strict_concatenate = true

[[tool.mypy.overrides]]
module = [
    "django.*",
    "arkad.*",
]
ignore_missing_imports = false

# Override for tests (excluded from typing rules)
[[tool.mypy.overrides]]
module = [
    "tests.*",
    "*.tests",
    "*.tests.*",
]
disallow_untyped_defs = false
disallow_incomplete_defs = false
ignore_missing_imports = true
check_untyped_defs = false
disallow_untyped_calls = false


# Override for migrations (skip most checks)
[[tool.mypy.overrides]]
module = [
    "migrations.*",
    "*.migrations.*",
]
disallow_untyped_defs = false
disallow_incomplete_defs = false
ignore_missing_imports = true
check_untyped_defs = false

# Override for API files (no typed return required)
[[tool.mypy.overrides]]
module = [
    "*.api",
    "*.api.*",
]
disallow_untyped_defs = false

[tool.django-stubs]
django_settings_module = "arkad.settings"
