# Generated by Django 5.2 on 2025-09-23 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySyncUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload a JSON file containing company data', upload_to='company_sync_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('companies_processed', models.IntegerField(default=0)),
                ('companies_created', models.IntegerField(default=0)),
                ('companies_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_sync_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Sync Upload',
                'verbose_name_plural': 'Company Sync Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
