# Generated by Django 5.2 on 2025-09-23 18:49

import arkad.utils
import functools
import jexpo_sync.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jexpo_sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysyncupload',
            options={'ordering': ['-uploaded_at'], 'permissions': [('can_upload_company_sync', 'Can upload company sync files')], 'verbose_name': 'Company Sync Upload', 'verbose_name_plural': 'Company Sync Uploads'},
        ),
        migrations.AlterField(
            model_name='companysyncupload',
            name='file',
            field=models.FileField(help_text='Upload a JSON file containing company data', upload_to=functools.partial(arkad.utils.unique_file_upload_path, *('private/company_sync',), **{}), validators=[jexpo_sync.models.validate_json_file]),
        ),
    ]
