# Generated by Django 5.2 on 2025-09-24 08:40

import arkad.utils
import functools
import jexpo_sync.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jexpo_sync', '0002_alter_companysyncupload_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysyncupload',
            name='file',
            field=models.FileField(help_text='Upload a JSON file containing company data', upload_to=functools.partial(arkad.utils.unique_file_upload_path, *('jexpo_sync',), **{}), validators=[jexpo_sync.models.validate_json_file]),
        ),
    ]
