# Generated by Django 5.1.6 on 2025-03-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
