# Generated by Django 5.1.6 on 2025-04-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0002_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
