# Generated by Django 5.2 on 2025-09-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0003_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='release_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='The time the event is released'),
        ),
    ]
