# Generated by Django 5.2 on 2025-10-02 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0004_event_release_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visible_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 19, 22, 0, tzinfo=datetime.timezone.utc), verbose_name='The time the event becomes visible'),
        ),
        migrations.AlterField(
            model_name='event',
            name='release_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 24, 22, 0, tzinfo=datetime.timezone.utc), null=True, verbose_name='The time the event is released'),
        ),
    ]
