# Generated by Django 5.2 on 2025-10-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0006_alter_ticket_notify_event_one_hour_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notify_registration_open_id',
            field=models.CharField(default=None, null=True),
        ),
    ]
