# Generated by Django 5.2 on 2025-10-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0006_alter_event_company'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='one_ticket_per_user_event',
        ),
    ]
