# Generated by Django 5.2 on 2025-10-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0007_remove_ticket_one_ticket_per_user_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='number_booked',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
