# Generated by Django 5.2 on 2025-10-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0007_event_notify_registration_open_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notify_registration_open_id',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='notify_event_one_hour_id',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='notify_event_tmrw_id',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
