# Generated by Django 5.2 on 2025-10-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0005_event_visible_time_alter_event_release_time'),
        ('event_booking', '0008_alter_event_notify_registration_open_id_and_more'),
    ]

    operations = [
    ]
