# Generated by Django 5.2 on 2025-10-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0009_merge_20251005_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='notify_event_one_hour_id',
            new_name='task_id_notify_event_in_one_hour',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='notify_event_tmrw_id',
            new_name='task_id_notify_event_tomorrow',
        ),
    ]
