# Generated by Django 5.2 on 2025-10-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0010_rename_notify_event_one_hour_id_ticket_task_id_notify_event_in_one_hour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='notify_registration_open_id',
            new_name='task_id_notify_registration_opening',
        ),
    ]
