# Generated by Django 5.2 on 2025-10-08 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0008_alter_event_number_booked'),
        ('event_booking', '0011_rename_notify_registration_open_id_event_task_id_notify_registration_opening'),
    ]

    operations = [
    ]
