# Generated by Django 5.2 on 2025-10-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0012_merge_20251008_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='task_id_notify_registration_closes',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='task_id_notify_event_in_one_hour',
            field=models.CharField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='task_id_notify_event_tomorrow',
            field=models.CharField(blank=True, default=None, editable=False, null=True),
        ),
    ]
