# Generated by Django 5.2 on 2025-10-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0013_event_task_id_notify_registration_closes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='task_id_notify_registration_closes',
        ),
        migrations.AddField(
            model_name='event',
            name='task_id_notify_registration_closing',
            field=models.CharField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='task_id_notify_registration_opening',
            field=models.CharField(blank=True, default=None, editable=False, null=True),
        ),
    ]
