# Generated by Django 5.2 on 2025-10-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0014_remove_event_task_id_notify_registration_closes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='task_id_notify_registration_closes_tomorrow',
            field=models.CharField(blank=True, default=None, editable=False, null=True),
        ),
    ]
