# Generated by Django 5.2 on 2025-10-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0015_ticket_task_id_notify_registration_closes_tomorrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='send_notifications_for_event',
            field=models.BooleanField(default=True, help_text='If false, no notifications will be sent for this event.'),
        ),
    ]
