# Generated by Django 5.2 on 2025-10-20 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0016_event_send_notifications_for_event'),
        ('notifications', '0007_scheduledcelerytasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='task_id_notify_registration_closing',
        ),
        migrations.RemoveField(
            model_name='event',
            name='task_id_notify_registration_opening',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='task_id_notify_event_in_one_hour',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='task_id_notify_event_tomorrow',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='task_id_notify_registration_closes_tomorrow',
        ),
        migrations.AddField(
            model_name='event',
            name='notify_registration_opening',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_event_registration_opening', to='notifications.scheduledcelerytasks'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='notify_event_in_one_hour',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_event_in_one_hour', to='notifications.scheduledcelerytasks'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='notify_event_tomorrow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_event_tomorrow', to='notifications.scheduledcelerytasks'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='notify_registration_closes_tomorrow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_registration_closes_tomorrow', to='notifications.scheduledcelerytasks'),
        ),
    ]
