# Generated by Django 5.2 on 2025-10-20 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0017_remove_event_task_id_notify_registration_closing_and_more'),
        ('notifications', '0007_scheduledcelerytasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='notify_event_in_one_hour',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_event_in_one_hour', to='notifications.scheduledcelerytasks'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='notify_event_tomorrow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_event_tomorrow', to='notifications.scheduledcelerytasks'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='notify_registration_closes_tomorrow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_registration_closes_tomorrow', to='notifications.scheduledcelerytasks'),
        ),
    ]
