# Generated by Django 5.2 on 2025-10-20 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0018_alter_ticket_notify_event_in_one_hour_and_more'),
        ('notifications', '0007_scheduledcelerytasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notify_registration_opening',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_event_registration_opening', to='notifications.scheduledcelerytasks'),
        ),
    ]
