# Generated by Django 5.2 on 2025-10-26 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0019_alter_event_notify_registration_opening'),
        ('notifications', '0008_scheduledcelerytasks_has_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notify_registration_opening',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_event_registration_opening', to='notifications.scheduledcelerytasks'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='notify_event_in_one_hour',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_event_in_one_hour', to='notifications.scheduledcelerytasks'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='notify_event_tomorrow',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_event_tomorrow', to='notifications.scheduledcelerytasks'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='notify_registration_closes_tomorrow',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_registration_closes_tomorrow', to='notifications.scheduledcelerytasks'),
        ),
    ]
