# Generated by Django 5.1.6 on 2025-03-08 20:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400, null=True)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('location', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('job_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('title', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('did_you_know', models.TextField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('url_linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('url_instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('url_facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('url_twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('url_youtube', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('student_session_motivation', models.TextField(blank=True, null=True)),
                ('days_with_studentsession', models.IntegerField(default=0)),
                ('desired_degrees', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD')], max_length=50), blank=True, default=list, size=None)),
                ('desired_programme', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('desired_competences', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Architecture', 'Architecture'), ('ArtificialIntelligence', 'Artificial Intelligence'), ('Usability', 'Usability'), ('Applications', 'Applications'), ('Automation', 'Automation'), ('Computation', 'Computation'), ('FireSafety', 'Fire Safety'), ('ComputerSecurity', 'Computer Security'), ('Design', 'Design'), ('EHealth', 'E-Health'), ('Electronics', 'Electronics'), ('EnergySystems', 'Energy Systems'), ('Law', 'Law'), ('Finance', 'Finance'), ('Geography', 'Geography'), ('Sustainability', 'Sustainability'), ('IndustrialProcesses', 'Industrial Processes'), ('Interactivity', 'Interactivity'), ('Chemistry', 'Chemistry'), ('Communications', 'Communications'), ('Construction', 'Construction'), ('FoodTechnology', 'Food Technology'), ('PharmaceuticalTechnology', 'Pharmaceutical Technology'), ('MathematicalModelling', 'Mathematical Modelling'), ('MaterialsEngineering', 'Materials Engineering'), ('LifeScience', 'Life Science'), ('Mechatronics', 'Mechatronics'), ('AccidentPrevention', 'Accident Prevention'), ('ProductDevelopment', 'Product Development'), ('Programming', 'Programming'), ('Planning', 'Planning'), ('ProjectManagement', 'Project Management'), ('RiskManagement', 'Risk Management'), ('TechnologyAndSociety', 'Technology and Society'), ('CivilEngineering', 'Civil Engineering'), ('Simulations', 'Simulations'), ('Manufacturing', 'Manufacturing'), ('InterdisciplinaryCompetences', 'Interdisciplinary Competences'), ('Physics', 'Physics')], max_length=50), blank=True, default=list, size=None)),
                ('positions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Thesis', 'Thesis'), ('TraineeEmployment', 'Trainee Employment'), ('Internship', 'Internship'), ('SummerJob', 'Summer Job'), ('ForeignOppurtunity', 'Foreign Opportunity'), ('PartTime', 'Part Time')], max_length=50), blank=True, default=list, size=None)),
                ('industries', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ElectricityEnergyPower', 'Electricity Energy Power'), ('Environment', 'Environment'), ('BankingFinance', 'Banking Finance'), ('Union', 'Union'), ('Investment', 'Investment'), ('Insurance', 'Insurance'), ('Recruitment', 'Recruitment'), ('Construction', 'Construction'), ('Architecture', 'Architecture'), ('GraphicDesign', 'Graphic Design'), ('DataIT', 'Data IT'), ('FinanceConsultancy', 'Finance Consultancy'), ('Telecommunication', 'Telecommunication'), ('Consulting', 'Consulting'), ('Management', 'Management'), ('Media', 'Media'), ('Industry', 'Industry'), ('NuclearPower', 'Nuclear Power'), ('LifeScience', 'Life Science'), ('MedicalTechniques', 'Medical Techniques'), ('PropertyInfrastructure', 'Property Infrastructure'), ('Research', 'Research'), ('Coaching', 'Coaching')], max_length=50), blank=True, default=list, size=None)),
                ('employees_locally', models.IntegerField(blank=True, default=None, null=True)),
                ('employees_globally', models.IntegerField(blank=True, default=None, null=True)),
                ('jobs', models.ManyToManyField(to='companies.job')),
            ],
        ),
    ]
