# Generated by Django 5.1.6 on 2025-04-05 11:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='desired_competences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Architecture', 'Architecture'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Usability', 'Usability'), ('Applications', 'Applications'), ('Automation', 'Automation'), ('Computation', 'Computation'), ('Fire Safety', 'Fire Safety'), ('Computer Security', 'Computer Security'), ('Design', 'Design'), ('E-Health', 'E-Health'), ('Electronics', 'Electronics'), ('Energy Systems', 'Energy Systems'), ('Law', 'Law'), ('Finance', 'Finance'), ('Geography', 'Geography'), ('Sustainability', 'Sustainability'), ('Industrial Processes', 'Industrial Processes'), ('Interactivity', 'Interactivity'), ('Chemistry', 'Chemistry'), ('Communications', 'Communications'), ('Construction', 'Construction'), ('Food Technology', 'Food Technology'), ('Pharmaceutical Technology', 'Pharmaceutical Technology'), ('Mathematical Modelling', 'Mathematical Modelling'), ('Materials Engineering', 'Materials Engineering'), ('Life Science', 'Life Science'), ('Mechatronics', 'Mechatronics'), ('Accident Prevention', 'Accident Prevention'), ('Product Development', 'Product Development'), ('Programming', 'Programming'), ('Planning', 'Planning'), ('Project Management', 'Project Management'), ('Risk Management', 'Risk Management'), ('Technology And Society', 'Technology and Society'), ('Civil Engineering', 'Civil Engineering'), ('Simulations', 'Simulations'), ('Manufacturing', 'Manufacturing'), ('Interdisciplinary Competences', 'Interdisciplinary Competences'), ('Physics', 'Physics')], max_length=50), blank=True, default=list, help_text='Choose from Architecture, Artificial Intelligence, Usability, Applications, Automation, Computation, Fire Safety, Computer Security, Design, E-Health, Electronics, Energy Systems, Law, Finance, Geography, Sustainability, Industrial Processes, Interactivity, Chemistry, Communications, Construction, Food Technology, Pharmaceutical Technology, Mathematical Modelling, Materials Engineering, Life Science, Mechatronics, Accident Prevention, Product Development, Programming, Planning, Project Management, Risk Management, Technology And Society, Civil Engineering, Simulations, Manufacturing, Interdisciplinary Competences, Physics', size=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='desired_degrees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD')], max_length=50), blank=True, default=list, help_text='Choose from Bachelor, Master, PhD', size=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='industries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Electricity Energy Power', 'Electricity Energy Power'), ('Environment', 'Environment'), ('Banking Finance', 'Banking Finance'), ('Union', 'Union'), ('Investment', 'Investment'), ('Insurance', 'Insurance'), ('Recruitment', 'Recruitment'), ('Construction', 'Construction'), ('Architecture', 'Architecture'), ('Graphic Design', 'Graphic Design'), ('Data IT', 'Data IT'), ('Finance Consultancy', 'Finance Consultancy'), ('Telecommunication', 'Telecommunication'), ('Consulting', 'Consulting'), ('Management', 'Management'), ('Media', 'Media'), ('Industry', 'Industry'), ('Nuclear Power', 'Nuclear Power'), ('Life Science', 'Life Science'), ('Medical Techniques', 'Medical Techniques'), ('Property Infrastructure', 'Property Infrastructure'), ('Research', 'Research'), ('Coaching', 'Coaching')], max_length=50), blank=True, default=list, help_text='Choose from Electricity Energy Power, Environment, Banking Finance, Union, Investment, Insurance, Recruitment, Construction, Architecture, Graphic Design, Data IT, Finance Consultancy, Telecommunication, Consulting, Management, Media, Industry, Nuclear Power, Life Science, Medical Techniques, Property Infrastructure, Research, Coaching', size=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='companies.job'),
        ),
        migrations.AlterField(
            model_name='company',
            name='positions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Thesis', 'Thesis'), ('Trainee Employment', 'Trainee Employment'), ('Internship', 'Internship'), ('Summer Job', 'Summer Job'), ('Foreign Opportunity', 'Foreign Opportunity'), ('Part Time', 'Part Time')], max_length=50), blank=True, default=list, help_text='Choose from Thesis, Trainee Employment, Internship, Summer Job, Foreign Opportunity, Part Time', size=None),
        ),
    ]
