# Generated by Django 5.2 on 2025-10-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_desired_competences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='visible_in_company_list',
            field=models.BooleanField(default=True, help_text='If false, the company will not be visible in the company list. Useful if a company for example only has a student session.'),
        ),
    ]
