services:
  db:
    restart: unless-stopped
    image: postgres:16
    volumes:
      - ${PWD}/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=arkad_db_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=arkad
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arkad_db_user -d arkad"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --save 300 1 --loglevel warning
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - app_network

  web:
    restart: unless-stopped
    build: ../arkad
    command: sh -c "
      python manage.py collectstatic --no-input &&
      python manage.py createcachetable &&
      python manage.py migrate &&
      gunicorn --workers 8 --timeout 16 arkad.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - static_volume:/app/arkad/static_root
      - media_volume:/app/arkad/media
      - ${PWD}/config:/app/arkad/config
      - ${PWD}/private:/app/arkad/private
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app_network

  celery-worker:
    build: ../arkad
    restart: unless-stopped
    # We do not need many concurrent workers as we are only sending notifications, they can be slightly delayed
    command: celery -A arkad worker -l info --concurrency=1 --worker-max-memory-per-child=1048576  # 1GB max memory per child
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - media_volume:/app/arkad/media
      - ${PWD}/config:/app/arkad/config
      - ${PWD}/private:/app/arkad/private
    networks:
      - app_network

  websocket:
    restart: unless-stopped
    build: ../arkad
    command: sh -c "daphne -b 0.0.0.0 -p 8001 arkad.asgi:application"
    volumes:
      - ${PWD}/config:/app/arkad/config
      - ${PWD}/private:/app/arkad/private
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app_network

  nginx:
    restart: unless-stopped
    image: nginx:latest
    volumes:
      - static_volume:/app/arkad/static_root:ro
      - media_volume:/app/arkad/media:rw
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
      - websocket
    networks:
      - app_network
      - traefik

volumes:
  media_volume:
  static_volume:
  redis_data:

networks:
  app_network:
    driver: bridge
  traefik:
    external: true
