services:
  db:
    restart: unless-stopped
    image: postgres:16
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=arkad_db_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=arkad
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arkad_db_user -d arkad"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --save 300 1 --loglevel warning
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - app_network

  web:
    restart: unless-stopped
    build: ../../arkad
    command: sh -c "
      python manage.py collectstatic --no-input &&
      python manage.py createcachetable && 
      python manage.py migrate &&
      gunicorn --workers 8 --timeout 16 arkad.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - static_volume:/app/arkad/static_root  # destination for collectstatic
      - media_volume:/app/arkad/media
      - ./config:/app/arkad/config
      - ./private:/app/arkad/private
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app_network

  celery-worker:
    build: ../../arkad
    restart: unless-stopped
    command: celery -A arkad worker -l info --concurrency=4
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - media_volume:/app/arkad/media
      - ./config:/app/arkad/config
      - ./private:/app/arkad/private
    networks:
      - app_network

  celery-beat:
    build: ../../arkad
    restart: unless-stopped
    command: sh -c "mkdir -p /app/arkad/celerybeat && celery -A arkad beat -l info -S django"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - media_volume:/app/arkad/media
      - ./config:/app/arkad/config
      - ./private:/app/arkad/private
      - celery_beat_schedule:/app/arkad/celerybeat
    networks:
      - app_network

  nginx:
    restart: unless-stopped
    image: nginx:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-staging.rule=Host(`staging.backend.arkadtlth.se`)"
      - "traefik.http.routers.app-staging.entrypoints=websecure"
      - "traefik.http.routers.app-staging.tls=true"
      - "traefik.http.routers.app-staging.tls.certresolver=production"
    volumes:
      - static_volume:/app/arkad/static_root:ro  # serve collected static files
      - media_volume:/app/arkad/media:rw
      - ../nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8081:80"
    expose:
      - 80
    depends_on:
      - web
    networks:
      - app_network
      - traefik

volumes:
  media_volume:
  static_volume:
  redis_data:
  celery_beat_schedule:

networks:
  app_network:
    driver: bridge
  traefik:
    external: true
