include:
  - ../shared-compose.yaml

services:
  nginx:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-staging.rule=Host(`staging.backend.arkadtlth.se`)"
      - "traefik.http.routers.app-staging.entrypoints=websecure"
      - "traefik.http.routers.app-staging.tls=true"
      - "traefik.http.routers.app-staging.tls.certresolver=production"
    ports:
      - "8081:80"
    expose:
      - 80
