# Generated by Django 5.1.6 on 2025-02-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_models", "0002_company_user_is_company_user_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
