# Generated by Django 5.1.6 on 2025-02-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_models", "0002_user_cv_user_food_preferences_user_is_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="last name"
            ),
        ),
    ]
