# Generated by Django 5.1.6 on 2025-02-27 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_models", "0003_alter_company_description_alter_company_name"),
        ("user_models", "0003_alter_user_first_name_alter_user_last_name"),
    ]

    operations = []
