# Generated by Django 5.1.6 on 2025-02-27 18:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0004_merge_20250227_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='days_at_arkad',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='company',
            name='desired_competences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Architecture', 'Architecture'), ('ArtificialIntelligence', 'Artificial Intelligence'), ('Usability', 'Usability'), ('Applications', 'Applications'), ('Automation', 'Automation'), ('Computation', 'Computation'), ('FireSafety', 'Fire Safety'), ('ComputerSecurity', 'Computer Security'), ('Design', 'Design'), ('EHealth', 'E-Health'), ('Electronics', 'Electronics'), ('EnergySystems', 'Energy Systems'), ('Law', 'Law'), ('Finance', 'Finance'), ('Geography', 'Geography'), ('Sustainability', 'Sustainability'), ('IndustrialProcesses', 'Industrial Processes'), ('Interactivity', 'Interactivity'), ('Chemistry', 'Chemistry'), ('Communications', 'Communications'), ('Construction', 'Construction'), ('FoodTechnology', 'Food Technology'), ('PharmaceuticalTechnology', 'Pharmaceutical Technology'), ('MathematicalModelling', 'Mathematical Modelling'), ('MaterialsEngineering', 'Materials Engineering'), ('LifeScience', 'Life Science'), ('Mechatronics', 'Mechatronics'), ('AccidentPrevention', 'Accident Prevention'), ('ProductDevelopment', 'Product Development'), ('Programming', 'Programming'), ('Planning', 'Planning'), ('ProjectManagement', 'Project Management'), ('RiskManagement', 'Risk Management'), ('TechnologyAndSociety', 'Technology and Society'), ('CivilEngineering', 'Civil Engineering'), ('Simulations', 'Simulations'), ('Manufacturing', 'Manufacturing'), ('InterdisciplinaryCompetences', 'Interdisciplinary Competences'), ('Physics', 'Physics')], max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='company',
            name='desired_degrees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD')], max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='company',
            name='desired_programme',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='company',
            name='did_you_know',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='host_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='host_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='host_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ElectricityEnergyPower', 'Electricity Energy Power'), ('Environment', 'Environment'), ('BankingFinance', 'Banking Finance'), ('Union', 'Union'), ('Investment', 'Investment'), ('Insurance', 'Insurance'), ('Recruitment', 'Recruitment'), ('Construction', 'Construction'), ('Architecture', 'Architecture'), ('GraphicDesign', 'Graphic Design'), ('DataIT', 'Data IT'), ('FinanceConsultancy', 'Finance Consultancy'), ('Telecommunication', 'Telecommunication'), ('Consulting', 'Consulting'), ('Management', 'Management'), ('Media', 'Media'), ('Industry', 'Industry'), ('NuclearPower', 'Nuclear Power'), ('LifeScience', 'Life Science'), ('MedicalTechniques', 'Medical Techniques'), ('PropertyInfrastructure', 'Property Infrastructure'), ('Research', 'Research'), ('Coaching', 'Coaching')], max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='positions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Thesis', 'Thesis'), ('TraineeEmployment', 'Trainee Employment'), ('Internship', 'Internship'), ('SummerJob', 'Summer Job'), ('ForeignOppurtunity', 'Foreign Opportunity'), ('PartTime', 'Part Time')], max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='company',
            name='student_session_motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
