# Generated by Django 5.2 on 2025-05-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0004_alter_user_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_company',
        ),
    ]
