# Generated by Django 5.2 on 2025-09-22 15:30

import arkad.utils
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0005_remove_user_is_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(arkad.utils.unique_file_upload_path, *('user/cv',), **{}), verbose_name='Users cv'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(arkad.utils.unique_file_upload_path, *('user/profile-picture',), **{}), verbose_name='User profile picture'),
        ),
    ]
