# Generated by Django 5.1.6 on 2025-03-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0005_company_days_at_arkad_company_desired_competences_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='host_email',
            new_name='company_email',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='host_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='host_phone',
            new_name='company_phone',
        ),
        migrations.AddField(
            model_name='company',
            name='days_with_studentsession',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='employees_globally',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='employees_locally',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
