# Generated by Django 5.1.6 on 2025-03-08 16:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0006_rename_host_email_company_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='desired_degrees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD')], max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='positions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Thesis', 'Thesis'), ('TraineeEmployment', 'Trainee Employment'), ('Internship', 'Internship'), ('SummerJob', 'Summer Job'), ('ForeignOppurtunity', 'Foreign Opportunity'), ('PartTime', 'Part Time')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
