# Generated by Django 5.1.6 on 2025-03-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0007_alter_company_desired_degrees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
