# Generated by Django 5.2 on 2025-10-05 09:32

from django.db import migrations


def migrate_programmes_to_english(apps, schema_editor):
    """Convert Swedish programme names to English"""
    User = apps.get_model('user_models', 'User')

    # Import the translation mapping from models
    from user_models.models import PROGRAMME_SWEDISH_TO_ENGLISH

    # Update all users with Swedish programme names to English
    for swedish_name, english_name in PROGRAMME_SWEDISH_TO_ENGLISH.items():
        User.objects.filter(programme=swedish_name).update(programme=english_name)


def reverse_migrate_programmes_to_swedish(apps, schema_editor):
    """Reverse migration: Convert English programme names back to Swedish"""
    User = apps.get_model('user_models', 'User')

    # Import the translation mapping from models
    from user_models.models import PROGRAMME_ENGLISH_TO_SWEDISH

    # Update all users with English programme names back to Swedish
    for english_name, swedish_name in PROGRAMME_ENGLISH_TO_SWEDISH.items():
        User.objects.filter(programme=english_name).update(programme=swedish_name)


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0007_user_fcm_token'),
    ]

    operations = [
        migrations.RunPython(migrate_programmes_to_english, reverse_migrate_programmes_to_swedish),
    ]
