# Generated by Django 5.2 on 2025-10-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0008_migrate_programme_to_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='programme',
            field=models.CharField(blank=True, choices=[('Fire Engineering', 'Brandingenjor'), ('Mechanical Engineering with Technical Design', 'Maskinteknik Td'), ('Electrical Engineering', 'Elektroteknik'), ('Environmental Engineering', 'Ekosystemteknik'), ('Mechanical Engineering', 'Maskinteknik'), ('Nanoscience and Technology', 'Nanoveteknik'), ('Biotechnology', 'Bioteknik'), ('Industrial Design', 'Industridesign'), ('Architecture', 'Arkitekt'), ('Information and Communication Engineering', 'Infokomm Teknik'), ('Chemical Engineering', 'Kemiteknik'), ('Civil Engineering with Railway Engineering', 'Bygg Jarnvag'), ('Road and Water Engineering', 'Vag Vatten'), ('Civil Engineering with Architecture', 'Bygg Arkitektur'), ('Industrial Engineering and Management', 'Industriell Ekonomi'), ('Engineering Mathematics', 'Teknisk Matematik'), ('Biomedical Engineering', 'Medicinteknik'), ('Surveying', 'Lantmateri'), ('Computer Engineering', 'Datateknik'), ('Engineering Physics', 'Teknisk Fysik'), ('Civil Engineering with Road and Traffic Engineering', 'Bygg Vag Trafik')], max_length=64, null=True),
        ),
    ]
