# Generated by Django 5.2 on 2025-10-07 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0009_alter_user_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffEnrollmentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_enrollment_tokens', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_enrollment_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Enrollment Token',
                'verbose_name_plural': 'Staff Enrollment Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
