# Generated by Django 5.2 on 2025-10-07 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0010_staffenrollmenttoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffenrollmenttoken',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='staffenrollmenttoken',
            name='used_at',
        ),
        migrations.RemoveField(
            model_name='staffenrollmenttoken',
            name='used_by',
        ),
        migrations.AddField(
            model_name='staffenrollmenttoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='StaffEnrollmentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='user_models.staffenrollmenttoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Enrollment Usage',
                'verbose_name_plural': 'Staff Enrollment Usages',
                'ordering': ['-created_at'],
                'unique_together': {('token', 'user')},
            },
        ),
    ]
