# Generated by Django 5.1.6 on 2025-03-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0010_alter_company_company_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='days_at_arkad',
        ),
    ]
