# Generated by Django 5.1.6 on 2025-03-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0014_alter_job_description_alter_job_link_alter_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
