# Generated by Django 5.1.6 on 2025-03-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_models', '0015_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
