# Generated by Django 5.2 on 2025-10-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_delete_notificationlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
