# Generated by Django 5.2 on 2025-10-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='auto_send_on_create',
            field=models.BooleanField(default=True, verbose_name='Should this be sent out automatically when created?'),
        ),
    ]
