# Generated by Django 5.2 on 2025-10-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_auto_send_on_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
