# Generated by Django 5.2 on 2025-10-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_email_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='fcm_link',
            field=models.URLField(blank=True, help_text='Link opened when notification is clicked', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(verbose_name='Body of notification or email body if email body not set'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='button_link',
            field=models.URLField(blank=True, help_text='Button link used in email', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Button text used in email'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='email_body',
            field=models.TextField(blank=True, null=True, verbose_name='Custom email body'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='greeting',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Greeting used in email'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heading used in email'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='note',
            field=models.TextField(blank=True, help_text='Note text used in email', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_topic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FCM Topic'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title for notification or subject for email'),
        ),
    ]
