# Generated by Django 5.2 on 2025-10-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_fcm_link_alter_notification_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledCeleryTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('task_arguments', models.JSONField(default=list)),
                ('task_id', models.CharField(editable=False, unique=True)),
                ('eta', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='PENDING', editable=False, max_length=255, null=True, verbose_name='Status, must be manually refreshed')),
                ('result', models.TextField(blank=True, editable=False, null=True)),
                ('error', models.TextField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
