# Generated by Django 5.2 on 2025-10-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_scheduledcelerytasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledcelerytasks',
            name='has_run',
            field=models.BooleanField(default=False),
        ),
    ]
