name: "arkad-backend-dev"

networks:
  traefik:
  app_network:

services:
  db:
    extends:
      file: ../deployment/shared-compose.yaml
      service: db
    container_name: arkad-dev-db
    environment:
      - POSTGRES_HOST=db
    env_file:
      - ../arkad/.env

  redis:
    extends:
      file: ../deployment/shared-compose.yaml
      service: redis
    container_name: arkad-dev-redis
    env_file:
      - ../arkad/.env

  web:
    extends:
      file: ../deployment/shared-compose.yaml
      service: web
    container_name: arkad-dev-web
    ports:
      - "8000:8000"
    environment:
      - SENTRY_ENVIRONMENT=development
      - DJANGO_DEBUG=True
      - POSTGRES_HOST=db
    command: >
      sh -c "
        mkdir -p /app/arkad/private &&
        cp -n /keys/* /app/arkad/private/ 2>/dev/null || true &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ../arkad:/app/arkad
      - static_volume:/app/arkad/static_root
      - media_volume:/app/arkad/media
      - ../config:/app/arkad/config
      - ../private:/app/arkad/private
    env_file:
      - ../arkad/.env

  celery-worker:
    extends:
      file: ../deployment/shared-compose.yaml
      service: celery-worker
    container_name: arkad-dev-celery-worker
    environment:
      - SENTRY_ENVIRONMENT=development
      - DJANGO_DEBUG=True
      - POSTGRES_HOST=db
    command: >
      sh -c "
        cp -n /keys/* /app/arkad/private/ 2>/dev/null || true &&
        celery -A arkad worker -l info --concurrency=1 --max-memory-per-child=1048576  # 1GB max memory per child
      "
    volumes:
      - ../arkad:/app/arkad
      - media_volume:/app/arkad/media
      - ../config:/app/arkad/config
      - ../private:/app/arkad/private
    env_file:
      - ../arkad/.env

  websocket:
    extends:
      file: ../deployment/shared-compose.yaml
      service: websocket
    container_name: arkad-dev-websocket
    ports:
      - "8001:8001"
    environment:
      - SENTRY_ENVIRONMENT=development
      - DJANGO_DEBUG=True
      - POSTGRES_HOST=db
    command: >
      sh -c "
        cp -n /keys/* /app/arkad/private/ 2>/dev/null || true &&
        daphne -b 0.0.0.0 -p 8001 arkad.asgi:application
      "
    volumes:
      - ../arkad:/app/arkad
      - ../config:/app/arkad/config
      - ../private:/app/arkad/private
    env_file:
      - ../arkad/.env

  nginx:
    extends:
      file: ../deployment/shared-compose.yaml
      service: nginx
    container_name: arkad-dev-nginx
    ports:
      - "8080:80"
    labels:
      - "traefik.enable=false"
    expose:
      - 80
    env_file:
      - ../arkad/.env

volumes:
  media_volume:
  static_volume:
  redis_data:
