# Generated by Django 5.1.6 on 2025-03-08 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('student_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='applicants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_representative', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='interviewee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviewee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='studentsession',
            constraint=models.UniqueConstraint(fields=('start_time', 'company'), name='No duplicated start time'),
        ),
        migrations.AddConstraint(
            model_name='studentsession',
            constraint=models.UniqueConstraint(fields=('interviewee', 'company'), name='A single user may only book one session per company'),
        ),
    ]
