# Generated by Django 5.1.6 on 2025-03-30 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('student_sessions', '0002_studentsession_applicants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsession',
            name='applicants',
        ),
        migrations.CreateModel(
            name='CompanyStudentSessionMotivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation_text', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSessionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_sessions.companystudentsessionmotivation')),
            ],
        ),
        migrations.AddField(
            model_name='studentsession',
            name='applications',
            field=models.ManyToManyField(to='student_sessions.studentsessionapplication'),
        ),
        migrations.AddConstraint(
            model_name='companystudentsessionmotivation',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='unique_student_session_motivation'),
        ),
    ]
