# Generated by Django 5.2 on 2025-05-19 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0005_rename_companystudentsessionmotivation_companystudentsessionapplicationinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsessionapplication',
            old_name='motivation',
            new_name='info',
        ),
        migrations.AddField(
            model_name='studentsessionapplication',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
