# Generated by Django 5.2 on 2025-05-19 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_desired_competences_and_more'),
        ('student_sessions', '0006_rename_motivation_studentsessionapplication_info_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSessionTimeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField(default=30, help_text='Duration of the student session in minutes')),
                ('booking_close_time', models.DateTimeField(blank=True, null=True)),
                ('time_booked', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='companystudentsessionapplicationinformation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companystudentsessionapplicationinformation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentsessionapplication',
            name='info',
        ),
        migrations.RemoveConstraint(
            model_name='studentsession',
            name='No duplicated start time',
        ),
        migrations.RemoveConstraint(
            model_name='studentsession',
            name='A single user may only book one session per company',
        ),
        migrations.RemoveField(
            model_name='studentsession',
            name='booking_close_time',
        ),
        migrations.RemoveField(
            model_name='studentsession',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='studentsession',
            name='interviewee',
        ),
        migrations.RemoveField(
            model_name='studentsession',
            name='start_time',
        ),
        migrations.AddField(
            model_name='studentsessionapplication',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsessionapplication',
            name='motivation_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsessionapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='studentsessionapplication',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='studentsessionapplication',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='unique_student_session_motivation'),
        ),
        migrations.AddField(
            model_name='studentsessiontimeslot',
            name='selected',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_sessions.studentsessionapplication'),
        ),
        migrations.AddField(
            model_name='studentsession',
            name='time_slots',
            field=models.ManyToManyField(to='student_sessions.studentsessiontimeslot'),
        ),
        migrations.DeleteModel(
            name='CompanyStudentSessionApplicationInformation',
        ),
    ]
