# Generated by Django 5.2 on 2025-05-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0007_studentsessiontimeslot_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsession',
            old_name='time_slots',
            new_name='timeslots',
        ),
        migrations.RemoveField(
            model_name='studentsessiontimeslot',
            name='booking_close_time',
        ),
        migrations.AddField(
            model_name='studentsession',
            name='booking_close_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsessionapplication',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='application/cv', verbose_name='Users cv'),
        ),
    ]
