# Generated by Django 5.2 on 2025-05-19 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0008_rename_time_slots_studentsession_timeslots_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsession',
            name='applications',
        ),
        migrations.RemoveField(
            model_name='studentsession',
            name='timeslots',
        ),
        migrations.AddField(
            model_name='studentsessionapplication',
            name='student_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_sessions.studentsession'),
        ),
        migrations.AddField(
            model_name='studentsessiontimeslot',
            name='student_session',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='student_sessions.studentsession'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentsessiontimeslot',
            name='selected',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_sessions.studentsessionapplication'),
        ),
    ]
