# Generated by Django 5.2 on 2025-05-19 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0009_remove_studentsession_applications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsessionapplication',
            name='student_session',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='student_sessions.studentsession'),
            preserve_default=False,
        ),
    ]
