# Generated by Django 5.2 on 2025-05-22 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_desired_competences_and_more'),
        ('student_sessions', '0010_alter_studentsessionapplication_student_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentsessionapplication',
            name='unique_student_session_motivation',
        ),
        migrations.RemoveField(
            model_name='studentsessionapplication',
            name='company',
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_representative', to='companies.company'),
        ),
        migrations.AddConstraint(
            model_name='studentsessionapplication',
            constraint=models.UniqueConstraint(fields=('student_session', 'user'), name='unique_student_session_motivation'),
        ),
        migrations.AddConstraint(
            model_name='studentsessiontimeslot',
            constraint=models.UniqueConstraint(fields=('student_session', 'start_time'), name='unique_student_session_timeslot'),
        ),
    ]
