# Generated by Django 5.2 on 2025-09-22 15:30

import arkad.utils
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0011_remove_studentsessionapplication_unique_student_session_motivation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsessionapplication',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=functools.partial(arkad.utils.unique_file_upload_path, *('application/cv',), **{}), verbose_name='Users cv'),
        ),
    ]
