# Generated by Django 5.2 on 2025-09-24 08:40

import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import student_sessions.dynamic_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0012_alter_studentsessionapplication_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='field_modifications',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default=student_sessions.dynamic_fields.FieldModificationSchema.student_session_modifications_default, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (student_sessions.dynamic_fields.FieldModificationSchema,))),
        ),
    ]
