# Generated by Django 5.2 on 2025-09-24 08:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0013_studentsession_field_modifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsession',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the student session, shown to students when applying', null=True),
        ),
        migrations.AddField(
            model_name='studentsession',
            name='disclaimer',
            field=models.TextField(blank=True, help_text='Disclaimer shown to students when applying (example SAAB requiring ONLY swedish citizens)', null=True),
        ),
    ]
