# Generated by Django 5.2 on 2025-10-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0014_studentsession_created_at_studentsession_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsessiontimeslot',
            name='notify_one_hour_id',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentsessiontimeslot',
            name='notify_tmrw_id',
            field=models.CharField(default=None, null=True),
        ),
    ]
