# Generated by Django 5.2 on 2025-09-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0014_studentsession_created_at_studentsession_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='booking_open_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='The time the student session is released/bookable'),
        ),
    ]
