# Generated by Django 5.2 on 2025-09-30 20:42

import datetime
from django.db import migrations, models, transaction
from arkad.defaults import STUDENT_SESSIONS_CLOSE_UTC, STUDENT_SESSIONS_OPEN_UTC


def set_default_booking_times(apps, schema_editor):
    """Fills in NULL values for the booking fields."""
    StudentSession = apps.get_model('student_sessions', 'StudentSession')

    with transaction.atomic():
        # Fill null booking_close_time
        StudentSession.objects.filter(booking_close_time__isnull=True).update(
            booking_close_time=STUDENT_SESSIONS_CLOSE_UTC
        )

        # Fill null booking_open_time
        StudentSession.objects.filter(booking_open_time__isnull=True).update(
            booking_open_time=STUDENT_SESSIONS_OPEN_UTC
        )

class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0015_studentsession_booking_open_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsession',
            name='booking_close_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 26, 22, 59, 59, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='booking_open_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 12, 22, 0, tzinfo=datetime.timezone.utc), verbose_name='The time the student session is released/bookable'),
        ),
        migrations.RunPython(set_default_booking_times, migrations.RunPython.noop), # Fill existing NULL values
    ]
