# Generated by Django 5.2 on 2025-09-30 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0016_alter_studentsession_booking_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsessiontimeslot',
            name='booking_closes_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 5, 22, 59, tzinfo=datetime.timezone.utc), help_text='The time the timeslot is no longer bookable'),
        ),
        migrations.AlterField(
            model_name='studentsession',
            name='booking_close_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 26, 22, 59, 59, tzinfo=datetime.timezone.utc), verbose_name='The time the student session is no longer bookable'),
        ),
    ]
