# Generated by Django 5.2 on 2025-09-30 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0017_studentsessiontimeslot_booking_closes_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsessiontimeslot',
            name='booking_closes_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 5, 22, 59, tzinfo=datetime.timezone.utc), help_text='The time the timeslot is no longer bookable', null=True),
        ),
    ]
