# Generated by Django 5.2 on 2025-10-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0015_studentsessiontimeslot_notify_one_hour_id_and_more'),
        ('student_sessions', '0018_alter_studentsessiontimeslot_booking_closes_at'),
    ]

    operations = [
    ]
