# Generated by Django 5.2 on 2025-10-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0018_alter_studentsessiontimeslot_booking_closes_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsessiontimeslot',
            name='selected',
        ),
        migrations.AddField(
            model_name='studentsession',
            name='session_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('company_event', 'Company Event')], default='regular', help_text='The type of the student session', max_length=20),
        ),
        migrations.AddField(
            model_name='studentsessiontimeslot',
            name='selected_applications',
            field=models.ManyToManyField(blank=True, help_text='Selected applications for this timeslot - supports multiple for company events', related_name='selected_timeslots', to='student_sessions.studentsessionapplication'),
        ),
    ]
