# Generated by Django 5.2 on 2025-10-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0019_merge_20251005_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsessiontimeslot',
            old_name='notify_one_hour_id',
            new_name='task_id_notify_timeslot_in_one_hour',
        ),
        migrations.RenameField(
            model_name='studentsessiontimeslot',
            old_name='notify_tmrw_id',
            new_name='task_id_notify_timeslot_tomorrow',
        ),
    ]
