# Generated by Django 5.2 on 2025-10-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0019_remove_studentsessiontimeslot_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='location',
            field=models.CharField(blank=True, help_text='Location of the student session, shown to students when applying', max_length=255, null=True),
        ),
    ]
