# Generated by Django 5.2 on 2025-10-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0020_studentsession_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='company_event_at',
            field=models.DateTimeField(blank=True, help_text='The date and time of the company event, if applicable', null=True),
        ),
    ]
