# Generated by Django 5.2 on 2025-10-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0020_rename_notify_one_hour_id_studentsessiontimeslot_task_id_notify_timeslot_in_one_hour_and_more'),
        ('student_sessions', '0021_studentsession_company_event_at'),
    ]

    operations = [
    ]
