# Generated by Django 5.2 on 2025-10-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0022_merge_20251008_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsessiontimeslot',
            name='task_id_notify_timeslot_in_one_hour',
        ),
        migrations.RemoveField(
            model_name='studentsessiontimeslot',
            name='task_id_notify_timeslot_tomorrow',
        ),
        migrations.AddField(
            model_name='studentsessionapplication',
            name='task_id_notify_timeslot_in_one_hour',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentsessionapplication',
            name='task_id_notify_timeslot_tomorrow',
            field=models.CharField(default=None, null=True),
        ),
    ]
