# Generated by Django 5.2 on 2025-10-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0023_remove_studentsessiontimeslot_task_id_notify_timeslot_in_one_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsessionapplication',
            name='task_notify_timeslot_booking_closes_tomorrow',
            field=models.CharField(default=None, null=True),
        ),
    ]
