# Generated by Django 5.2 on 2025-10-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0024_studentsessionapplication_task_notify_timeslot_booking_closes_tomorrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='name',
            field=models.CharField(blank=True, help_text='Name for the session, if not used the company name is shown', max_length=255, null=True),
        ),
    ]
