# Generated by Django 5.2 on 2025-10-10 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0025_studentsession_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsessiontimeslot',
            name='booking_closes_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 5, 22, 59, tzinfo=datetime.timezone.utc), help_text='The time the timeslot is no longer bookable'),
        ),
    ]
