# Generated by Django 5.2 on 2025-10-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0026_alter_studentsessiontimeslot_booking_closes_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsessionapplication',
            name='task_id_notify_timeslot_in_one_hour',
            field=models.CharField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='studentsessionapplication',
            name='task_id_notify_timeslot_tomorrow',
            field=models.CharField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='studentsessionapplication',
            name='task_notify_timeslot_booking_closes_tomorrow',
            field=models.CharField(default=None, editable=False, null=True),
        ),
    ]
