# Generated by Django 5.2 on 2025-10-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0027_alter_studentsessionapplication_task_id_notify_timeslot_in_one_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='task_id_notify_registration_open',
            field=models.CharField(default=None, editable=False, null=True),
        ),
    ]
