# Generated by Django 5.2 on 2025-10-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0028_studentsession_task_id_notify_registration_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsession',
            name='task_id_notify_registration_close',
            field=models.CharField(default=None, editable=False, null=True),
        ),
    ]
