# Generated by Django 5.2 on 2025-10-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_sessions', '0029_studentsession_task_id_notify_registration_close'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsession',
            name='task_id_notify_registration_close',
        ),
    ]
