# Generated by Django 5.2 on 2025-10-11 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_desired_competences_and_more'),
        ('student_sessions', '0030_remove_studentsession_task_id_notify_registration_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsession',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_representative', to='companies.company'),
        ),
    ]
