# Generated by Django 5.2 on 2025-10-20 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_scheduledcelerytasks'),
        ('student_sessions', '0031_alter_studentsession_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsession',
            name='task_id_notify_registration_open',
        ),
        migrations.RemoveField(
            model_name='studentsessionapplication',
            name='task_id_notify_timeslot_in_one_hour',
        ),
        migrations.RemoveField(
            model_name='studentsessionapplication',
            name='task_id_notify_timeslot_tomorrow',
        ),
        migrations.RemoveField(
            model_name='studentsessionapplication',
            name='task_notify_timeslot_booking_closes_tomorrow',
        ),
        migrations.AddField(
            model_name='studentsession',
            name='notify_registration_open',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_session_notify_registration_open', to='notifications.scheduledcelerytasks'),
        ),
        migrations.AddField(
            model_name='studentsessionapplication',
            name='notify_timeslot_booking_closes_tomorrow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_timeslot_booking_closes_tomorrow', to='notifications.scheduledcelerytasks'),
        ),
        migrations.AddField(
            model_name='studentsessionapplication',
            name='notify_timeslot_in_one_hour',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_timeslot_in_one_hour', to='notifications.scheduledcelerytasks'),
        ),
        migrations.AddField(
            model_name='studentsessionapplication',
            name='notify_timeslot_tomorrow',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_timeslot_tomorrow', to='notifications.scheduledcelerytasks'),
        ),
    ]
