# Generated by Django 5.2 on 2025-10-20 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_scheduledcelerytasks'),
        ('student_sessions', '0032_remove_studentsession_task_id_notify_registration_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsession',
            name='notify_registration_open',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_session_notify_registration_open', to='notifications.scheduledcelerytasks'),
        ),
        migrations.AlterField(
            model_name='studentsessionapplication',
            name='notify_timeslot_booking_closes_tomorrow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_timeslot_booking_closes_tomorrow', to='notifications.scheduledcelerytasks'),
        ),
        migrations.AlterField(
            model_name='studentsessionapplication',
            name='notify_timeslot_in_one_hour',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_timeslot_in_one_hour', to='notifications.scheduledcelerytasks'),
        ),
        migrations.AlterField(
            model_name='studentsessionapplication',
            name='notify_timeslot_tomorrow',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_timeslot_tomorrow', to='notifications.scheduledcelerytasks'),
        ),
    ]
