name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  lint-typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requirements.txt

      - name: Run ruff
        run: ruff check . --fix

      - name: Run mypy
        run: mypy --config-file pyproject.toml .

  deploy:
    needs: lint-typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@51.21.44.86 'cd /home/ec2-user/arkad-backend/deployment/staging/ && bash deploy.sh'
