name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run deployment script
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-44-201-157-224.compute-1.amazonaws.com 'cd /etc/arkad/arkad-backend-django/deployment/staging/ && bash deploy.sh'